#Eigen value & Eigen vecotr

In [ ]:
import numpy as np

In [ ]:
A = np.array([
    [1,2],
    [3,4]
])

eigenvalues, egienvectors = np.linalg.eig(A)

print(eigenvalues)
print(egienvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

#singular value Decomposition(SVD)<br>
used in data compression

In [ ]:
U ,S ,VT = np.linalg.svd(A)
print("U matrix:  \n",U)
print("Sigma matrix:  \n",S)
print("VT matrix:  \n",VT)

U matrix:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Sigma matrix:
 [5.4649857  0.36596619]
VT matrix:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]

In [ ]:
print(U @ U.T)

[[1.00000000e+00 3.00701513e-16]
 [3.00701513e-16 1.00000000e+00]]

#Pandas Basis

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

#series

In [ ]:
import pandas as pd

a = ['g','e','f','s']
res = pd.Series(a)
print(res)

0    g
1    e
2    f
3    s
dtype: object

In [ ]:
import pandas as pd

a ={
    "name":"nelson",
    "age":23,
    "city":"ktm"
}
res = pd.Series(a)
print(res)

name    nelson
age         23
city       ktm
dtype: object

In [ ]:
res.ndim

1

#dataframe<br>
combination of rows and column

In [ ]:
import pandas as pd

a ={
    "name":"nelson",
    "age":23,
    "city":"ktm"
}
res = pd.Series(a)
print(res)

name    nelson
age         23
city       ktm
dtype: object

In [ ]:
res_data = pd.DataFrame(res,columns=["data"])
print(res_data)

        data
name  nelson
age       23
city     ktm

In [ ]:
res_data.ndim

2

In [ ]:
res_data['data']

name    nelson
age         23
city       ktm
Name: data, dtype: object

In [ ]:
import pandas as pd

a ={
    "name":['Nelson','ram','sita'],
    "age":[23,24,None],
    "city":['ktm','lalitpur','jhapa']
}
df = pd.DataFrame(a)
df

     name   age      city
0  Nelson  23.0       ktm
1     ram  24.0  lalitpur
2    sita   NaN     jhapa

In [ ]:
df.to_csv('data.csv', index=False)

In [ ]:
df['name']

0    Nelson
1       ram
2      sita
Name: name, dtype: object

In [ ]:
df[['name','age']]

     name   age
0  Nelson  23.0
1     ram  24.0
2    sita   NaN

In [ ]:
df[['name','age','city']]

     name   age      city
0  Nelson  23.0       ktm
1     ram  24.0  lalitpur
2    sita   NaN     jhapa

In [ ]:
df['age'].isna()

0    False
1    False
2     True
Name: age, dtype: bool

In [ ]:
print(df['age'].isna().sum())

1

In [ ]:
res = df.loc[df['name']=='Nelson']
res

     name   age city
0  Nelson  23.0  ktm

In [ ]:
df.to_csv('data.csv',index=False)

In [ ]:
data = pd.read_csv("data.csv")
data

     name   age      city
0  Nelson  23.0       ktm
1     ram  24.0  lalitpur
2    sita   NaN     jhapa

## Difference between `loc` and `iloc`

In pandas, both `.loc` and `.iloc` are used for selecting data from a DataFrame, but they differ in how they interpret their indexing arguments:

*   **`.loc` (Label-based indexing)**:
    *   Selects data based on the **labels** of rows and columns.
    *   Can accept a single label, a list of labels, a slice of labels, or a boolean array.
    *   The end of the slice is **inclusive** when using labels (e.g., `df.loc['A':'C']` includes 'C').

*   **`.iloc` (Integer-location based indexing)**:
    *   Selects data based on the **integer positions** of rows and columns.
    *   Can accept a single integer, a list of integers, a slice of integers, or a boolean array.
    *   The end of the slice is **exclusive** when using integers (e.g., `df.iloc[0:3]` includes rows 0, 1, 2 but not 3), similar to Python's standard slicing.

In [ ]:
# Example of iloc: Select the first two rows and all columns
res_iloc = df.iloc[0:2]
print("DataFrame selected using iloc (first two rows):\n", res_iloc)

# Example of iloc: Select row at index 1 and column at index 0
# (which corresponds to 'ram' and 'name' respectively)
value_iloc = df.iloc[1, 0]
print("\nValue selected using iloc (row index 1, column index 0):", value_iloc)

DataFrame selected using iloc (first two rows):
      name   age      city
0  Nelson  23.0       ktm
1     ram  24.0  lalitpur

Value selected using iloc (row index 1, column index 0): ram